USE [master]
GO
/****** Object:  Database [seguralta]    Script Date: 29/05/2019 20:24:22 ******/
CREATE DATABASE [seguralta]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'seguralta', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\seguralta.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'seguralta_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\seguralta_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [seguralta] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [seguralta].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [seguralta] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [seguralta] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [seguralta] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [seguralta] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [seguralta] SET ARITHABORT OFF 
GO
ALTER DATABASE [seguralta] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [seguralta] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [seguralta] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [seguralta] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [seguralta] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [seguralta] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [seguralta] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [seguralta] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [seguralta] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [seguralta] SET  ENABLE_BROKER 
GO
ALTER DATABASE [seguralta] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [seguralta] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [seguralta] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [seguralta] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [seguralta] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [seguralta] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [seguralta] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [seguralta] SET RECOVERY FULL 
GO
ALTER DATABASE [seguralta] SET  MULTI_USER 
GO
ALTER DATABASE [seguralta] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [seguralta] SET DB_CHAINING OFF 
GO
ALTER DATABASE [seguralta] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [seguralta] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [seguralta] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'seguralta', N'ON'
GO
ALTER DATABASE [seguralta] SET QUERY_STORE = OFF
GO
USE [seguralta]
GO
/****** Object:  Table [dbo].[Contato]    Script Date: 29/05/2019 20:24:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contato](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Pessoa] [int] NULL,
	[Email] [varchar](150) NULL,
	[DDD] [varchar](3) NULL,
	[Telefone] [varchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pessoa]    Script Date: 29/05/2019 20:24:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pessoa](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](300) NULL,
	[Cidade] [varchar](300) NULL,
	[Estado] [varchar](150) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StatusMensagemEnviada]    Script Date: 29/05/2019 20:24:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StatusMensagemEnviada](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Pessoa] [int] NULL,
	[Contato] [int] NULL,
	[Assunto] [varchar](1000) NULL,
	[MensagemEnviada] [varchar](max) NULL,
	[RetornoSite] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tabelaContato]    Script Date: 29/05/2019 20:24:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tabelaContato](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Pessoa] [int] NULL,
	[Email] [varchar](150) NULL,
	[DDD] [varchar](3) NULL,
	[Telefone] [varchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tabelaPessoa]    Script Date: 29/05/2019 20:24:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tabelaPessoa](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](300) NULL,
	[Cidade] [varchar](300) NULL,
	[Estado] [varchar](150) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Contato]  WITH CHECK ADD FOREIGN KEY([Pessoa])
REFERENCES [dbo].[Pessoa] ([Id])
GO
ALTER TABLE [dbo].[StatusMensagemEnviada]  WITH CHECK ADD FOREIGN KEY([Contato])
REFERENCES [dbo].[tabelaContato] ([Id])
GO
ALTER TABLE [dbo].[StatusMensagemEnviada]  WITH CHECK ADD FOREIGN KEY([Pessoa])
REFERENCES [dbo].[tabelaPessoa] ([Id])
GO
ALTER TABLE [dbo].[tabelaContato]  WITH CHECK ADD FOREIGN KEY([Pessoa])
REFERENCES [dbo].[tabelaPessoa] ([Id])
GO
USE [master]
GO
ALTER DATABASE [seguralta] SET  READ_WRITE 
GO
